### ISSUE TITLE
CentOS8向けパッケージが存在しない

### ISSUE THREAD

**Issue by dewfalse** [milter-manager/milter-manager#142] opened 2021-05-28 06:31 UTC
CentOS7向けのパッケージまでしか存在せず、CentOS8向けのパッケージが存在しません。

**Comment by kenhys** [comment] 2021-05-31 03:03
TODO:

* [ ] build package on centos8
* [ ] upload package to packagecloud to enable yum repository
* [ ] update https://milter-manager.osdn.jp/reference/install-to.html (Add link to CentOS 8)
* [ ] update https://milter-manager.osdn.jp/reference/install-to-centos.html (CentOS 8 installation document)

**Comment by kenhys** [comment] 2021-05-31 05:29
In the future release, it may be better not to depend on rinse. (sometimes bootstrap fails)

**Comment by kenhys** [comment] 2021-05-31 05:36
`/etc/rinse/centos-8.packages` is incomplete for centos-linux-release, centos-linux-repos and libmodulemd.
we should better to feedback to upstream.

**Comment by kenhys** [comment] 2021-05-31 05:41
libmodulemd is required by python3-dnf.

```
# rpm -q --whatrequires libmodulemd
python3-dnf-4.2.23-4.el8.noarch
```

**Comment by kenhys** [comment] 2021-05-31 07:19
> /etc/rinse/centos-8.packages is incomplete for centos-linux-release, centos-linux-repos and libmodulemd.
we should better to feedback to upstream.

Since CentOS 8.3, these packages are renamed.

**Comment by kenhys** [comment] 2021-05-31 07:29
The problem that .service file is not installed was fixed via https://github.com/milter-manager/milter-manager/commit/bab7ecd2d6c54679597038b7621e29a35d0d1be8

**Comment by kenhys** [comment] 2021-05-31 07:37
The issue that cron.d/milter-manager-log is not installed was fixed via https://github.com/milter-manager/milter-manager/commit/5852c33512a26a5f1b9f61004fa1ff5f838ef109

**Comment by kenhys** [comment] 2021-05-31 07:38
Now `make build CENTOS_VERSIONS=8` builds the following packages:
```
% find centos
centos
centos/8
centos/8/stable
centos/8/stable/x86_64
centos/8/stable/x86_64/Packages
centos/8/stable/x86_64/Packages/milter-manager-debugsource-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-client-devel-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-server-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/ruby-milter-client-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-core-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/milter-manager-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-compatible-devel-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-server-devel-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/ruby-milter-server-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-core-devel-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/milter-manager-devel-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-client-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/ruby-milter-core-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-client-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/milter-manager-log-analyzer-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/milter-manager-libs-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/milter-manager-doc-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/ruby-milter-server-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-compatible-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/milter-manager-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/ruby-milter-client-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-core-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-server-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/ruby-milter-core-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/libmilter-compatible-debuginfo-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/milter-manager-munin-plugins-2.1.5-1.el8.x86_64.rpm
centos/8/stable/x86_64/Packages/milter-manager-libs-2.1.5-1.el8.x86_64.rpm
centos/8/stable/source
centos/8/stable/source/SRPMS
centos/8/stable/source/SRPMS/milter-manager-2.1.5-1.el8.src.rpm
```

**Comment by kenhys** [comment] 2021-05-31 09:21
Oops, test build is weird.

```
$ sudo /usr/sbin/milter-manager -u milter-manager -g milter-manager --show-config

** (process:39687): WARNING **: 09:20:10.389: /usr/lib64/milter-manager/module/configuration/milter-manager-ruby-configuration.so: undefined symbol: rbg_rval2cstr

** (process:39687): WARNING **: 09:20:10.390: /usr/lib64/milter-manager/module/configuration/milter-manager-ruby-configuration.so: undefined symbol: rbg_rval2cstr
[2021-05-31T09:20:10.390329Z]: [GLib-GObject] g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
[2021-05-31T09:20:10.390359Z]: [GLib-GObject] invalid (NULL) pointer instance
[2021-05-31T09:20:10.390382Z]: [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[2021-05-31T09:20:10.390405Z]: [GLib-GObject] invalid (NULL) pointer instance
[2021-05-31T09:20:10.390416Z]: [GLib-GObject] g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[2021-05-31T09:20:10.390434Z]: [GLib-GObject] g_type_instance_get_private: assertion 'instance != NULL && instance->g_class != NULL' failed
Segmentation fault
```

**Comment by kenhys** [comment] 2021-06-01 05:07
On https://github.com/milter-manager/milter-manager/issues/142#issuecomment-851352546 environment,

```
$ rpm -qa|grep milter
milter-greylist-4.6.2-11.el8.x86_64
libmilter-client-2.1.5-1.el8.x86_64
ruby-milter-core-2.1.5-1.el8.x86_64
ruby-milter-client-2.1.5-1.el8.x86_64
milter-manager-devel-2.1.5-1.el8.x86_64
sendmail-milter-8.15.2-32.el8.x86_64
spamass-milter-postfix-0.4.0-13.el8.noarch
libmilter-core-2.1.5-1.el8.x86_64
libmilter-server-2.1.5-1.el8.x86_64
libmilter-client-devel-2.1.5-1.el8.x86_64
libmilter-server-devel-2.1.5-1.el8.x86_64
ruby-milter-server-2.1.5-1.el8.x86_64
libmilter-compatible-2.1.5-1.el8.x86_64
milter-manager-2.1.5-1.el8.x86_64
spamass-milter-0.4.0-13.el8.x86_64
clamav-milter-0.103.2-1.el8.x86_64
libmilter-core-devel-2.1.5-1.el8.x86_64
milter-manager-libs-2.1.5-1.el8.x86_64
libmilter-compatible-devel-2.1.5-1.el8.x86_64
```

**Comment by kenhys** [comment] 2021-06-01 05:33
On CentOS8, ldd is not broken.

```
$ ldd /usr/lib64/milter-manager/module/configuration/milter-manager-ruby-configuration.so|sort
        /lib64/ld-linux-x86-64.so.2 (0x00007f070e4d4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f070c1df000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f070b2af000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f070b770000)
        libffi.so.6 => /lib64/libffi.so.6 (0x00007f070b974000)
        libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f070cc9a000)
        libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00007f070d1b5000)
        libgmp.so.10 => /lib64/libgmp.so.10 (0x00007f070b4d8000)
        libgnutls.so.30 => /lib64/libgnutls.so.30 (0x00007f070bdee000)
        libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f070d3b9000)
        libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f070cfb3000)
        libhogweed.so.4 => /lib64/libhogweed.so.4 (0x00007f070a35f000)
        libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f070ad5e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f070d60c000)
        libmilter-client.so.0 => /lib64/libmilter-client.so.0 (0x00007f070de6c000)
        libmilter-core.so.0 => /lib64/libmilter-core.so.0 (0x00007f070d98e000)
        libmilter-manager.so.0 => /lib64/libmilter-manager.so.0 (0x00007f070e08e000)
        libmilter-server.so.0 => /lib64/libmilter-server.so.0 (0x00007f070dc56000)
        libnettle.so.6 => /lib64/libnettle.so.6 (0x00007f070a590000)
        libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007f070af7c000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f070bb7d000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f070c5a2000)
        libruby.so.2.5 => /lib64/libruby.so.2.5 (0x00007f070c7c2000)
        libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007f070a7ca000)
        libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f070a9dd000)
        linux-vdso.so.1 (0x00007ffd255d6000)
```

And it seems that binding is built but symbol is not resolved.

```
[vagrant@centos8 ~]$ nm -D /usr/lib64/milter-manager/module/configuration/milter-manager-ruby-configuration.so|grep rbg_
                 U rbg_rval2cstr
[vagrant@centos8 ~]$ nm -D /usr/lib64/milter-manager/binding/ext/glib2.so | grep "rbg_rval2cstr$"
0000000000035ee0 T rbg_rval2cstr
$ rpm -qf /usr/lib64/milter-manager/binding/ext/glib2.so
ruby-milter-core-2.1.5-1.el8.x86_64
```

**Comment by kenhys** [comment] 2021-06-01 05:48
Is it hardening issue?

**Comment by kenhys** [comment] 2021-06-01 05:49
> Is it hardening issue?

I'll check whether it hits or not.

**Comment by kenhys** [comment] 2021-06-01 06:24
That's it. if `%undefine _hardened_build` is set, it works as expected.

**Comment by kenhys** [comment] 2021-06-01 06:45
With some try&error, SEGV is caused by `-Wl,-z,now`.

**Comment by kenhys** [comment] 2021-06-01 07:33
Now, `sudo /usr/sbin/milter-manager -u milter-manager -g milter-manager --show-config` works.

**Comment by kenhys** [comment] 2021-06-01 07:37
milter-test-server fails...

```
$ sudo -u milter-manager -H milter-test-server -s unix:/var/run/milter-manager/milter-manager.sock

[2021-06-01T07:36:42.915210Z]: [1] [agent][error][decode] Decode error: milter-decoder-error-quark:3: unexpected reply was received: 
[2021-06-01T07:36:42.915363Z]: [1] [writer][write][error] can't write to not started or shutdown channel
[2021-06-01T07:36:42.915396Z]: [1] [server][error][write] [milter-test-server] Failed to write to milter: milter-writer-error-quark:2: can't
 write to not started or shutdown channel

** (milter-test-server:664657): CRITICAL **: 16:36:42.915: milter_event_loop_quit: assertion 'priv->depth > 0' failed

** (milter-test-server:664657): CRITICAL **: 16:36:42.915: milter_event_loop_quit: assertion 'priv->depth > 0' failed
Failed to write to milter: milter-writer-error-quark:2: can't write to not started or shutdown channel
```

**Comment by kenhys** [comment] 2021-06-01 07:47
> milter-test-server fails...
> 
> ```
> $ sudo -u milter-manager -H milter-test-server -s unix:/var/run/milter-manager/milter-manager.sock
> 
> [2021-06-01T07:36:42.915210Z]: [1] [agent][error][decode] Decode error: milter-decoder-error-quark:3: unexpected reply was received: 
> [2021-06-01T07:36:42.915363Z]: [1] [writer][write][error] can't write to not started or shutdown channel
> [2021-06-01T07:36:42.915396Z]: [1] [server][error][write] [milter-test-server] Failed to write to milter: milter-writer-error-quark:2: can't
>  write to not started or shutdown channel
> 
> ** (milter-test-server:664657): CRITICAL **: 16:36:42.915: milter_event_loop_quit: assertion 'priv->depth > 0' failed
> 
> ** (milter-test-server:664657): CRITICAL **: 16:36:42.915: milter_event_loop_quit: assertion 'priv->depth > 0' failed
> Failed to write to milter: milter-writer-error-quark:2: can't write to not started or shutdown channel
> ```

It seems that incomplete clamav-milter cause it.

**Comment by kenhys** [comment] 2021-06-01 08:00
If clamav-milter is stopped, milter-test-server works

```
$ sudo -u milter-manager -H milter-test-server -s unix:/var/run/milter-manager/milter-manager.sock
[2021-06-01T07:54:59.059198Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059282Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059330Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059366Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059387Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059407Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059427Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059442Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059460Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059476Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059491Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059507Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059521Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059540Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059556Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059571Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059586Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059600Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
[2021-06-01T07:54:59.059617Z]: [1] [server][reply][quitted][quit][accept] [milter-test-server]
status: accept
elapsed-time: 5.01235 seconds
```

**Comment by kenhys** [comment] 2021-06-01 08:41
CentOS 8 packages were uploaded!

**Comment by kenhys** [comment] 2021-06-01 09:54
document is also updated.
https://milter-manager.osdn.jp/reference/install-to-centos.html

**Comment by kenhys** [comment] 2021-06-01 09:57
Done!

**Closed by kenhys** 2021-06-01 09:57 UTC
